italy = {'Piemonte': {'local_id': '01', 'iso_id': 'IT-21'},
    'Valle-d-Aosta': {'local_id': '02', 'iso_id': 'IT-23'},
    'Lombardia': {'local_id': '03', 'iso_id': 'IT-25'},
    'Trentino-Alto_Adige': {'local_id': '04', 'iso_id': 'IT-32'},
    'Veneto': {'local_id': '05', 'iso_id': 'IT-34'},
    'Friuli-Venezia-Giulia': {'local_id': '06', 'iso_id': 'IT-36'},
    'Liguria': {'local_id': '07', 'iso_id': 'IT-42'},
    'Emilia-Romagna': {'local_id': '08', 'iso_id': 'IT-45'},
    'Toscana': {'local_id': '09', 'iso_id': 'IT-52'},
    'Umbria': {'local_id': '10', 'iso_id': 'IT-55'},
    'Marche': {'local_id': '11', 'iso_id': 'IT-57'},
    'Lazio': {'local_id': '12', 'iso_id': 'IT-62'},
    'Abruzzo': {'local_id': '13', 'iso_id': 'IT-65'},
    'Molise': {'local_id': '14', 'iso_id': 'IT-67'},
    'Campania': {'local_id': '15', 'iso_id': 'IT-72'},
    'Puglia': {'local_id': '16', 'iso_id': 'IT-75'},
    'Basilicata': {'local_id': '17', 'iso_id': 'IT-77'},
    'Calabria': {'local_id': '18', 'iso_id': 'IT-78'},
    'Sicilia': {'local_id': '19', 'iso_id': 'IT-82'},
    'Sardegna': {'local_id': '20', 'iso_id': 'IT-88'}}

us = {'Alabama': {'iso_id': 'US-AL'},
    'Alaska': {'iso_id': 'US-AK'},
    'Arizona': {'iso_id': 'US-AZ'},
    'Arkansas': {'iso_id': 'US-AR'},
    'California': {'iso_id': 'US-CA'},
    'Colorado': {'iso_id': 'US-CO'},
    'Connecticut': {'iso_id': 'US-CT'},
    'Delaware': {'iso_id': 'US-DE'},
    'Florida': {'iso_id': 'US-FL'},
    'Georgia': {'iso_id': 'US-GA'},
    'Hawaii': {'iso_id': 'US-HI'},
    'Idaho': {'iso_id': 'US-ID'},
    'Illinois': {'iso_id': 'US-IL'},
    'Indiana': {'iso_id': 'US-IN'},
    'Iowa': {'iso_id': 'US-IA'},
    'Kansas': {'iso_id': 'US-KS'},
    'Kentucky': {'iso_id': 'US-KY'},
    'Louisiana': {'iso_id': 'US-LA'},
    'Maine': {'iso_id': 'US-ME'},
    'Maryland': {'iso_id': 'US-MD'},
    'Massachusetts': {'iso_id': 'US-MA'},
    'Michigan': {'iso_id': 'US-MI'},
    'Minnesota': {'iso_id': 'US-MN'},
    'Mississippi': {'iso_id': 'US-MS'},
    'Missouri': {'iso_id': 'US-MO'},
    'Montana': {'iso_id': 'US-MT'},
    'Nebraska': {'iso_id': 'US-NE'},
    'Nevada': {'iso_id': 'US-NV'},
    'New Hampshire': {'iso_id': 'US-NH'},
    'New Jersey': {'iso_id': 'US-NJ'},
    'New Mexico': {'iso_id': 'US-NM'},
    'New York': {'iso_id': 'US-NY'},
    'North Carolina': {'iso_id': 'US-NC'},
    'North Dakota': {'iso_id': 'US-ND'},
    'Ohio': {'iso_id': 'US-OH'},
    'Oklahoma': {'iso_id': 'US-OK'},
    'Oregon': {'iso_id': 'US-OR'},
    'Pennsylvania': {'iso_id': 'US-PA'},
    'Rhode Island': {'iso_id': 'US-RI'},
    'South Carolina': {'iso_id': 'US-SC'},
    'South Dakota': {'iso_id': 'US-SD'},
    'Tennessee': {'iso_id': 'US-TN'},
    'Texas': {'iso_id': 'US-TX'},
    'Utah': {'iso_id': 'US-UT'},
    'Vermont': {'iso_id': 'US-VT'},
    'Virginia': {'iso_id': 'US-VA'},
    'Washington': {'iso_id': 'US-WA'},
    'West Virginia': {'iso_id': 'US-WV'},
    'Wisconsin': {'iso_id': 'US-WI'},
    'Wyoming': {'iso_id': 'US-WY'},
    'District of Columbia': {'iso_id': 'US-DC'}}

spain = {'Andalucia': {'iso_id': 'ES-AN', 'local_id': 'AN'},
    'Aragon': {'iso_id': 'ES-AR', 'local_id': 'AR'},
    'Principado de Asturias': {'iso_id': 'ES-AS', 'local_id': 'AS'},
    'Canarias': {'iso_id': 'ES-CN', 'local_id': 'CN'},
    'Cantabria': {'iso_id': 'ES-CB', 'local_id': 'CB'},
    'Castilla y Leon': {'iso_id': 'ES-CL', 'local_id': 'CL'},
    'Castilla-La Mancha': {'iso_id': 'ES-CM', 'local_id': 'CM'},
    'Catalunya': {'iso_id': 'ES-CT', 'local_id': 'CT'},
    'Euskal Herria': {'iso_id': 'ES-PV', 'local_id': 'PV'},
    'Extremadura': {'iso_id': 'ES-EX', 'local_id': 'EX'},
    'Galicia': {'iso_id': 'ES-GA', 'local_id': 'GA'},
    'Illes Balears': {'iso_id': 'ES-IB', 'local_id': 'IB'},
    'La Rioja': {'iso_id': 'ES-RI', 'local_id': 'RI'},
    'Comunidad de Madrid': {'iso_id': 'ES-MD', 'local_id': 'MD'},
    'Region de Murcia': {'iso_id': 'ES-MC', 'local_id': 'MC'},
    'Nafarroako Foru Komunitatea': {'iso_id': 'ES-NC', 'local_id': 'NC'},
    'Comunidad Valenciana': {'iso_id': 'ES-VC', 'local_id': 'VC'}}

france_sub_regions = {'1': 'FR-V',
    '2': 'FR-S',
    '3': 'FR-C',
    '4': 'FR-U',
    '6': 'FR-U',
    '7': 'FR-V',
    '8': 'FR-G',
    '9': 'FR-N',
    '10': 'FR-G',
    '11': 'FR-K',
    '12': 'FR-N',
    '67': 'FR-A',
    '13': 'FR-U',
    '14': 'FR-P',
    '15': 'FR-C',
    '16': 'FR-T',
    '17': 'FR-T',
    '18': 'FR-F',
    '19': 'FR-L',
    '2A': 'FR-H',
    '21': 'FR-D',
    '22': 'FR-E',
    '23': 'FR-L',
    '79': 'FR-T',
    '24': 'FR-B',
    '25': 'FR-I',
    '26': 'FR-V',
    '91': 'FR-J',
    '27': 'FR-Q',
    '28': 'FR-F',
    '29': 'FR-E',
    '30': 'FR-K',
    '32': 'FR-N',
    '33': 'FR-B',
    '2B': 'FR-H',
    '31': 'FR-N',
    '43': 'FR-C',
    '52': 'FR-G',
    '5': 'FR-U',
    '70': 'FR-I',
    '74': 'FR-V',
    '65': 'FR-N',
    '87': 'FR-L',
    '68': 'FR-A',
    '92': 'FR-J',
    '34': 'FR-K',
    '35': 'FR-E',
    '36': 'FR-F',
    '37': 'FR-F',
    '38': 'FR-V',
    '39': 'FR-I',
    '40': 'FR-B',
    '42': 'FR-V',
    '44': 'FR-R',
    '45': 'FR-F',
    '41': 'FR-F',
    '46': 'FR-N',
    '47': 'FR-B',
    '48': 'FR-K',
    '49': 'FR-R',
    '50': 'FR-P',
    '51': 'FR-G',
    '53': 'FR-R',
    '54': 'FR-M',
    '55': 'FR-M',
    '56': 'FR-E',
    '57': 'FR-M',
    '58': 'FR-D',
    '59': 'FR-O',
    '60': 'FR-S',
    '61': 'FR-P',
    '75': 'FR-J',
    '62': 'FR-O',
    '63': 'FR-C',
    '64': 'FR-B',
    '66': 'FR-K',
    '69': 'FR-V',
    '71': 'FR-D',
    '72': 'FR-R',
    '73': 'FR-V',
    '77': 'FR-J',
    '76': 'FR-Q',
    '93': 'FR-J',
    '80': 'FR-S',
    '81': 'FR-N',
    '82': 'FR-N',
    '90': 'FR-I',
    '94': 'FR-J',
    '95': 'FR-J',
    '83': 'FR-U',
    '84': 'FR-U',
    '85': 'FR-R',
    '86': 'FR-T',
    '88': 'FR-M',
    '89': 'FR-D',
    '78': 'FR-J'}

france = {'Alsace': {'iso_id': 'FR-A'},
    'Aquitaine': {'iso_id': 'FR-B'},
    'Auvergne': {'iso_id': 'FR-C'},
    'Bourgogne': {'iso_id': 'FR-D'},
    'Bretagne': {'iso_id': 'FR-E'},
    'Centre-Val-de-Loire': {'iso_id': 'FR-F'},
    'Champagne-Ardenne': {'iso_id': 'FR-G'},
    'Corse': {'iso_id': 'FR-H'},
    'Franche-Comte': {'iso_id': 'FR-I'},
    'Ile-de-France': {'iso_id': 'FR-J'},
    'Languedoc-Roussillon': {'iso_id': 'FR-K'},
    'Limousin': {'iso_id': 'FR-L'},
    'Lorraine': {'iso_id': 'FR-M'},
    'Midi-Pyrenees': {'iso_id': 'FR-N'},
    'Nord-Pas-de-Calais': {'iso_id': 'FR-O'},
    'Basse-Normandie': {'iso_id': 'FR-P'},
    'Haute-Normandie': {'iso_id': 'FR-Q'},
    'Pays-de-la-Loire': {'iso_id': 'FR-R'},
    'Picardie': {'iso_id': 'FR-S'},
    'Poitou-Charentes': {'iso_id': 'FR-T'},
    'Provence-Alpes-Cote-d-Azur': {'iso_id': 'FR-U'},
    'Rhone-Alpes': {'iso_id': 'FR-V'}}

brazil = {'Distrito Federal': {'local_id': 'DF', 'iso_id': 'BR-DF'},
    'Acre': {'local_id': 'AC', 'iso_id': 'BR-AC'},
    'Alagoas': {'local_id': 'AL', 'iso_id': 'BR-AL'},
    'Amapa': {'local_id': 'AP', 'iso_id': 'BR-AP'},
    'Amazonas': {'local_id': 'AM', 'iso_id': 'BR-AM'},
    'Bahia': {'local_id': 'BA', 'iso_id': 'BR-BA'},
    'Ceara': {'local_id': 'CE', 'iso_id': 'BR-CE'},
    'Espirito Santo': {'local_id': 'ES', 'iso_id': 'BR-ES'},
    'Goias': {'local_id': 'GO', 'iso_id': 'BR-GO'},
    'Maranhao': {'local_id': 'MA', 'iso_id': 'BR-MA'},
    'Mato Grosso': {'local_id': 'MT', 'iso_id': 'BR-MT'},
    'Mato Grosso do Sul': {'local_id': 'MS', 'iso_id': 'BR-MS'},
    'Minas Gerais': {'local_id': 'MG', 'iso_id': 'BR-MG'},
    'Parana': {'local_id': 'PR', 'iso_id': 'BR-PR'},
    'Paraiba': {'local_id': 'PB', 'iso_id': 'BR-PB'},
    'Para': {'local_id': 'PA', 'iso_id': 'BR-PA'},
    'Pernambuco': {'local_id': 'PE', 'iso_id': 'BR-PE'},
    'Piaui': {'local_id': 'PI', 'iso_id': 'BR-PI'},
    'Rio Grande do Norte': {'local_id': 'RN', 'iso_id': 'BR-RN'},
    'Rio Grande do Sul': {'local_id': 'RS', 'iso_id': 'BR-RS'},
    'Rio de Janeiro': {'local_id': 'RJ', 'iso_id': 'BR-RJ'},
    'Rondonia': {'local_id': 'RO', 'iso_id': 'BR-RO'},
    'Roraima': {'local_id': 'RR', 'iso_id': 'BR-RR'},
    'Santa Catarina': {'local_id': 'SC', 'iso_id': 'BR-SC'},
    'Sergipe': {'local_id': 'SE', 'iso_id': 'BR-SE'},
    'Sao Paulo': {'local_id': 'SP', 'iso_id': 'BR-SP'},
    'Tocantins': {'local_id': 'TO', 'iso_id': 'BR-TO'}}